stages:
  - build
  - test
  - deploy

job:
  stage: build
  script:
    - echo "Building..."

test:
  stage: test
  script:
    - echo "Running tests..."

deploy:
  stage: deploy
  script:
    - |
      #set -e
      #echo "CI_COMMIT_BRANCH: $CI_COMMIT_BRANCH"
      #echo "CI_JOB_TOKEN: $CI_JOB_TOKEN"
      
      # Configure Git user
      git config --local user.email "ishaqbuic@gmail.com.com" # Use your GitHub email here
      git config --local user.name "ishaqbuic" # Use your GitHub username here

      # Check if the remote already exists before adding
      if ! git remote | grep -q 'origin'; then
        git remote add origin https://github.com/ishaqbuic/test_repo.git
      fi

      # Checkout production branch
      git checkout -B production origin/production

      # Pull latest changes from origin
      git pull origin production

      # Display current status
      git status

      # Commit and push changes to GitHub
      git add .
      git commit -m "Auto push from GitLab CI/CD pipeline - Production"
      git push origin production:main # Change 'main' if necessary
  only:
    - production
