deploy:
  stage: deploy
  script:
    - >
      
      # Clone GitHub repository
      git clone https://github.com/ishaqbuic/test_repo.git
      cd test_repo

      echo "Cloning repository"
      # Configure Git user
      git config --local user.email "ishaqbuic@gmail.com.com" # Use your GitHub email here
      git config --local user.name "ishaqbuic" # Use your GitHub username here

      echo "Github configuration done"

      # Add GitHub repository as remote
      #git remote add github https://github.com/ishaqbuic/test_repo.git
      echo "add remote github"

      # Checkout production branch
      git checkout main
      echo "checkout main done"


      # Pull latest changes from origin and GitHub
      git pull origin main
      git pull github main
      echo "pull  done"

      # Display current status
      git status

      # Commit and push changes to GitHub
      git add .
      git commit -m "Auto push from GitLab CI/CD pipeline - Production"
      git push github main:main
      echo "push  done"
  only:
    - main    
      
