deploy:
  stage: deploy
  script:
    - >
      set -e
      echo "CI_COMMIT_BRANCH: $CI_COMMIT_BRANCH"
      echo "CI_JOB_TOKEN: $CI_JOB_TOKEN"
      
      # Clone GitHub repository
      git clone https://github.com/ishaqbuic/test_repo.git
      cd test_repo

      # Configure Git user
      git config --local user.email "ishaqbuic@gmail.com.com" # Use your GitHub email here
      git config --local user.name "ishaqbuic" # Use your GitHub username here


      # Add GitHub repository as remote
      git remote add github https://github.com/ishaqbuic/test_repo.git

      # Checkout production branch
      git checkout production

      # Pull latest changes from origin and GitHub
      git pull origin production
      git pull github production

      # Display current status
      git status

      # Commit and push changes to GitHub
      git add .
      git commit -m "Auto push from GitLab CI/CD pipeline - Production"
      git push github production:main
  only:
    - production    
      
