stages:
  - push_to_github

push_to_github:
  stage: push_to_github
  script:
    - echo "cloning repo"
    - git clone https://github.com/ishaqbuic/test_repo.git
    - cd test_repo
    - pwd
    - ls
    - echo "Cloning done"
    - git config --local user.email "ishaqbuic@gmail.com" # Fix the typo here
    - git config --local user.name "ishaqbuic" # Use your GitHub username here
    - echo "Github configuration done"

     # Add GitHub repository as remote
    - git remote add github https://github.com/ishaqbuic/test_repo.git # Uncomment this line
    - echo "Github remote add done"
    # Checkout main branch
    - git checkout main
    - echo "checkout main done"
      
       #Pull latest changes from origin and GitHub
    - git pull -f origin main
    - git pull github main # Make sure the branch name is correct here
    - echo "pull done"

  # Display current status
    - git status

    - echo "machine github.com login ishaqbuic password $GITHUB_TOKEN" > ~/.netrc
    - git push github main
    - echo "push done"
  only:
    - main
