stages:
  - push_to_github

push_to_github:
  stage: push_to_github
  script:
    - echo "cloning repo"
    - git clone https://ishaqbuic@github.com/ishaqbuic/test_repo.git 
    - pwd
    - ls
    - echo "Cloning done"
    - git config --local user.email "ishaqbuic@gmail.com" # Fix the typo here
    - git config --local user.name "ishaqbuic" # Use your GitHub username here
    - echo "Github configuration done"

     # Add GitHub repository as remote    
    - git remote add github https://ishaqbuic@github.com/ishaqbuic/test_repo.git    
    - echo "Github remote add done"
    # Checkout main branch
    - git checkout main
    - echo "checkout origin main done"
       #Pull latest changes from origin and GitHub
    - git pull origin main
    - git push github main
 # Make sure the branch name is correct here
    - echo "push done"
  only:
    - main