stages:
  - push_to_github

push_to_github:
  stage: push_to_github
  script:
    - git config --local user.email "ishaqbuic@gmail.com" # Fix the typo here
    - git config --local user.name "ishaqbuic" # Use your GitHub username here

    - git remote add github https://github.com/ishaqbuic/test_repo.git
    - git push github $CI_COMMIT_SHA:refs/heads/main
  only:
    - main
