stages:
  - push_to_github

push_to_github:
  stage: push_to_github
  script:
    #- echo "Cloning repo"
    #- git clone https://gitlab.com/devops2771812/repo_push_test.git
    #- echo "gitlab cloning done"
    #- cd repo_push_test
    - pwd 
    - ls
   
    
    - git config --local user.email "ishaqbuic@gmail.com"
    - git config --local user.name "ishaqbuic"
    - echo "Github configuration done"

    - git remote add github https://ishaqbuic@github.com/ishaqbuic/test_repo.git
    - echo "Github remote add done"

    - git checkout main
    - echo "Checkout origin main done"
    - git branch
    - git pull origin main
    
    - git add .
    - git commit -m "push from gitlab" 

    - git push github main 
    - echo "Push done"
  only:
    - main
