stages:
  - push_to_github

push_to_github:
  stage: push_to_github
  script:
    - echo "cloning repo"
    - git clone https://github.com/ishaqbuic/test_repo.git
    - cd test_repo
    - pwd
    - ls
    - echo "Cloning done"
    - git config --local user.email "ishaqbuic@gmail.com" # Fix the typo here
    - git config --local user.name "ishaqbuic" # Use your GitHub username here

    - git remote add github https://github.com/ishaqbuic/test_repo.git
    - echo "machine github.com login ishaqbuic password $GITHUB_TOKEN" > ~/.netrc
    - git push github $CI_COMMIT_SHA:refs/heads/main
  only:
    - main
